const roMonths=["gennaio","febbraio","marzo","aprile","maggio","giugno","luglio","agosto","settembre","ottobre","novembre","dicembre"],roDays=["domenica","lunedì","martedì","mercoledì","giovedì","venerdì","sabato"];
function easter(y){let a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),day=(h+l-7*m+114)%31+1;return new Date(y,mo-1,day)}
function add(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x} function iso(d){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")}
let selected=new Date(),shown=new Date(selected.getFullYear(),selected.getMonth(),1);
async function loadRemote(d){try{
const url="https://parolaviva.art/api/v1/letture/"+d.getFullYear()+"/"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")+".json";
const r=await fetch(url);if(!r.ok)throw new Error("Dati liturgici non disponibili");const x=await r.json();if(selected.toDateString()!=d.toDateString())return;
if(x.celebrazione)document.querySelector("#feast").textContent=x.celebrazione;
const color=x.colore||"";document.querySelector("#rank").innerHTML='<span class="vestment '+litColorClass(color)+'" aria-hidden="true"><span></span></span><strong>'+escapeHtml(cap(color))+'</strong>';
const l=x.letture||{},refs=[l.prima,l.salmo,l.seconda,l.vangelo].filter(Boolean).map(v=>v.riferimento).filter(Boolean);
document.querySelector("#gospelRef").textContent=l.vangelo?.riferimento||"Vangelo del giorno";
if(l.vangelo?.testo)document.querySelector("#gospelText").innerHTML='<div class="gospel-full">'+formatBible(l.vangelo.testo)+'</div><a class="source-link" href="https://parolaviva.art/opendata" target="_blank" rel="noopener">Fonte: Parola Viva · Bibbia Martini →</a>';
else document.querySelector("#gospelText").textContent="Testo del Vangelo non disponibile.";
document.querySelector("#meditation").textContent=meditationFor(x.celebrazione,l.vangelo?.riferimento||"");
document.querySelector("#saintLife").textContent=x.celebrazione?"Oggi la liturgia celebra "+x.celebrazione+". Questa sezione sarà arricchita con una presentazione storica e spirituale specifica della celebrazione.":"";
document.querySelector("#prayer").textContent=prayerFor(x.celebrazione||"",color);
}catch(e){console.warn("Calendario liturgico italiano non disponibile",e)}}
function cap(v){return v?v.charAt(0).toUpperCase()+v.slice(1):""}
function formatBible(v){if(Array.isArray(v))return v.map(x=>escapeHtml(typeof x==="string"?x:(x.t||x.testo||""))).join(" ");return escapeHtml(typeof v==="string"?v:(v.testo||""))}
function meditationFor(title,ref){return "Il Vangelo di oggi"+(ref?" ("+ref+")":"")+" ci invita a fermarci davanti alla Parola e a lasciarla entrare nella vita concreta. Non basta ascoltare: il Vangelo domanda una risposta, un cambiamento dello sguardo e un gesto capace di trasformare ciò che viviamo. "+(title?"La celebrazione di "+title+" ci ricorda che la santità nasce dalla fedeltà quotidiana a Dio. ":"")+"Possiamo domandarci quali parole di Gesù ci interpellano oggi, quali resistenze portiamo nel cuore e quale passo concreto possiamo compiere. La fede cresce quando la Parola diventa scelta, servizio, perdono e attenzione verso chi incontriamo. Prendiamoci qualche momento di silenzio, rileggiamo lentamente il Vangelo e affidiamo al Signore ciò che stiamo vivendo, chiedendogli di riconoscere la sua presenza anche nelle situazioni più semplici della giornata."}
function escapeHtml(v){return String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function litColorClass(c){c=(c||"").toLowerCase();if(c.includes("verde"))return"green";if(c.includes("rosso"))return"red";if(c.includes("viola"))return"violet";if(c.includes("rosa"))return"rose";return"white"}
function prayerFor(title,color){const name=title||"questa giornata liturgica";return "Signore Dio nostro, ti ringraziamo per il dono di questo giorno e per la Parola con cui continui a parlarci. Nella celebrazione di "+name+", apri la nostra mente e il nostro cuore perché possiamo riconoscere la tua presenza. Rafforza la nostra fede nelle difficoltà, donaci coraggio nelle scelte, pazienza con le persone che incontriamo e un cuore capace di perdonare. Fa’ che non siamo soltanto ascoltatori del Vangelo, ma testimoni attraverso le nostre azioni. Proteggi le nostre famiglie, sostieni i malati, consola chi è solo e accompagna chi sta attraversando un momento difficile. Guidaci nelle nostre responsabilità e rendici strumenti della tua pace. Per Cristo nostro Signore. Amen."}
function renderDay(d){selected=new Date(d);document.querySelector("#weekday").textContent=roDays[d.getDay()]+",";document.querySelector("#day").textContent=d.getDate();document.querySelector("#month").textContent=roMonths[d.getMonth()]+" "+d.getFullYear();document.querySelector("#feast").textContent="Caricamento celebrazione…";document.querySelector("#rank").textContent="Calendario Romano";document.querySelector("#gospelRef").textContent="Vangelo del giorno";document.querySelector("#gospelText").textContent="Caricamento del Vangelo…";document.querySelector("#saintLife").textContent="Caricamento della celebrazione…";document.querySelector("#meditation").textContent="Preparazione della meditazione del giorno…";document.querySelector("#prayer").textContent="Preparazione della preghiera del giorno…";shown=new Date(d.getFullYear(),d.getMonth(),1);loadRemote(d)}
function renderCalendar(){document.querySelector("#calendarTitle").textContent=roMonths[shown.getMonth()]+" "+shown.getFullYear();const grid=document.querySelector("#calendarGrid");grid.innerHTML="";let first=(shown.getDay()+6)%7,start=new Date(shown.getFullYear(),shown.getMonth(),1-first);for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let b=document.createElement("button");b.className="day-cell";b.textContent=d.getDate();if(d.getMonth()!=shown.getMonth())b.classList.add("other");let now=new Date();if(d.toDateString()==now.toDateString())b.classList.add("today");if(d.toDateString()==selected.toDateString())b.classList.add("selected");b.onclick=()=>{renderDay(d);renderCalendar();openView("today")};grid.appendChild(b)}}
function openView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.view===id));if(id==="calendar")renderCalendar()}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>openView(b.dataset.view));document.querySelector("#prevMonth").onclick=()=>{shown.setMonth(shown.getMonth()-1);renderCalendar()};document.querySelector("#nextMonth").onclick=()=>{shown.setMonth(shown.getMonth()+1);renderCalendar()};document.querySelector("#goToday").onclick=()=>{renderDay(new Date());renderCalendar()};renderDay(new Date());renderCalendar();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");