const roMonths=["ianuarie","februarie","martie","aprilie","mai","iunie","iulie","august","septembrie","octombrie","noiembrie","decembrie"],roDays=["duminică","luni","marți","miercuri","joi","vineri","sâmbătă"];
const fixed={
"01-01":["Sfânta Fecioară Maria, Născătoare de Dumnezeu","Solemnitate"],"01-02":["Sfinții Vasile cel Mare și Grigore din Nazianz","Memorie"],"01-17":["Sfântul Anton, abate","Memorie"],"01-25":["Convertirea Sfântului Paul, apostol","Sărbătoare"],"01-26":["Sfinții Timotei și Tit, episcopi","Memorie"],"01-28":["Sfântul Toma de Aquino, preot și învățător al Bisericii","Memorie"],"01-31":["Sfântul Ioan Bosco, preot","Memorie"],
"02-02":["Întâmpinarea Domnului","Sărbătoare"],"02-05":["Sfânta Agata, fecioară și martiră","Memorie"],"02-06":["Sfinții Paul Miki și însoțitorii, martiri","Memorie"],"02-10":["Sfânta Scolastica, fecioară","Memorie"],"02-14":["Sfinții Ciril, călugăr, și Metodiu, episcop","Memorie"],"02-22":["Catedra Sfântului Petru, apostol","Sărbătoare"],
"03-19":["Sfântul Iosif, soțul Sfintei Fecioare Maria","Solemnitate"],"03-25":["Buna Vestire","Solemnitate"],
"04-25":["Sfântul Marcu, evanghelist","Sărbătoare"],"04-29":["Sfânta Ecaterina de Siena, fecioară și învățătoare a Bisericii","Memorie"],
"05-01":["Sfântul Iosif Muncitorul","Memorie facultativă"],"05-03":["Sfinții Filip și Iacob, apostoli","Sărbătoare"],"05-14":["Sfântul Matia, apostol","Sărbătoare"],"05-31":["Vizita Sfintei Fecioare Maria","Sărbătoare"],
"06-01":["Sfântul Iustin, martir","Memorie"],"06-11":["Sfântul Barnaba, apostol","Memorie"],"06-13":["Sfântul Anton de Padova, preot și învățător al Bisericii","Memorie"],"06-24":["Nașterea Sfântului Ioan Botezătorul","Solemnitate"],"06-28":["Sfântul Irineu, episcop, martir și învățător al Bisericii","Memorie"],"06-29":["Sfinții Petru și Paul, apostoli","Solemnitate"],
"07-03":["Sfântul Toma, apostol","Sărbătoare"],"07-11":["Sfântul Benedict, abate","Memorie"],"07-22":["Sfânta Maria Magdalena","Sărbătoare"],"07-25":["Sfântul Iacob, apostol","Sărbătoare"],"07-26":["Sfinții Ioachim și Ana, părinții Sfintei Fecioare Maria","Memorie"],"07-29":["Sfinții Marta, Maria și Lazăr","Memorie"],
"08-06":["Schimbarea la Față a Domnului","Sărbătoare"],"08-08":["Sfântul Dominic, preot","Memorie"],"08-10":["Sfântul Laurențiu, diacon și martir","Sărbătoare"],"08-11":["Sfânta Clara, fecioară","Memorie"],"08-15":["Adormirea Maicii Domnului","Solemnitate"],"08-20":["Sfântul Bernard, abate și învățător al Bisericii","Memorie"],"08-21":["Sfântul Pius al X-lea, papă","Memorie"],"08-22":["Sfânta Fecioară Maria Regină","Memorie"],"08-24":["Sfântul Bartolomeu, apostol","Sărbătoare"],"08-27":["Sfânta Monica","Memorie"],"08-28":["Sfântul Augustin, episcop și învățător al Bisericii","Memorie"],"08-29":["Martiriul Sfântului Ioan Botezătorul","Memorie"],
"09-03":["Sfântul Grigore cel Mare, papă și învățător al Bisericii","Memorie"],"09-08":["Nașterea Sfintei Fecioare Maria","Sărbătoare"],"09-14":["Înălțarea Sfintei Cruci","Sărbătoare"],"09-15":["Sfânta Fecioară Maria Îndurerată","Memorie"],"09-21":["Sfântul Matei, apostol și evanghelist","Sărbătoare"],"09-23":["Sfântul Pius din Pietrelcina, preot","Memorie"],"09-27":["Sfântul Vincențiu de Paul, preot","Memorie"],"09-29":["Sfinții Arhangheli Mihail, Gabriel și Rafael","Sărbătoare"],"09-30":["Sfântul Ieronim, preot și învățător al Bisericii","Memorie"],
"10-01":["Sfânta Tereza a Pruncului Isus, fecioară și învățătoare a Bisericii","Memorie"],"10-02":["Sfinții Îngeri Păzitori","Memorie"],"10-04":["Sfântul Francisc de Assisi","Memorie"],"10-07":["Sfânta Fecioară Maria a Rozariului","Memorie"],"10-15":["Sfânta Tereza a lui Isus, fecioară și învățătoare a Bisericii","Memorie"],"10-17":["Sfântul Ignațiu de Antiohia, episcop și martir","Memorie"],"10-18":["Sfântul Luca, evanghelist","Sărbătoare"],"10-28":["Sfinții Simon și Iuda, apostoli","Sărbătoare"],
"11-01":["Toți Sfinții","Solemnitate"],"11-02":["Pomenirea tuturor credincioșilor răposați","Comemorare"],"11-04":["Sfântul Carol Borromeu, episcop","Memorie"],"11-09":["Sfințirea Bazilicii din Lateran","Sărbătoare"],"11-10":["Sfântul Leon cel Mare, papă și învățător al Bisericii","Memorie"],"11-11":["Sfântul Martin de Tours, episcop","Memorie"],"11-21":["Prezentarea Sfintei Fecioare Maria","Memorie"],"11-30":["Sfântul Andrei, apostol","Sărbătoare"],
"12-03":["Sfântul Francisc Xaveriu, preot","Memorie"],"12-07":["Sfântul Ambroziu, episcop și învățător al Bisericii","Memorie"],"12-08":["Neprihănita Zămislire a Sfintei Fecioare Maria","Solemnitate"],"12-13":["Sfânta Lucia, fecioară și martiră","Memorie"],"12-14":["Sfântul Ioan al Crucii, preot și învățător al Bisericii","Memorie"],"12-25":["Nașterea Domnului","Solemnitate"],"12-26":["Sfântul Ștefan, primul martir","Sărbătoare"],"12-27":["Sfântul Ioan, apostol și evanghelist","Sărbătoare"],"12-28":["Sfinții Prunci Nevinovați, martiri","Sărbătoare"]
};
const readings2026={"09-02":"1Cor 3,1-9; Ps 32; Lc 4,38-44","09-04":"1Cor 4,1-5; Ps 36; Lc 5,33-39","09-05":"1Cor 4,6b-15; Ps 144; Lc 6,1-5","09-06":"Ez 33,7-9; Ps 94; Rom 13,8-10; Mt 18,15-20","09-09":"1Cor 7,25-31; Ps 44; Lc 6,20-26","09-11":"1Cor 9,16-19.22b-27; Ps 83; Lc 6,39-42","09-14":"Num 21,4b-9; Ps 77; Fil 2,6-11; In 3,13-17","09-19":"1Cor 15,35-37.42-49; Ps 55; Lc 8,4-15","09-24":"Qoh 1,2-11; Ps 89; Lc 9,7-9","09-25":"Qoh 3,1-11; Ps 143; Lc 9,18-22","09-27":"Ez 18,25-28; Ps 24; Fil 2,1-11; Mt 21,28-32","09-28":"Iob 1,6-22; Ps 16; Lc 9,46-50","09-30":"Iob 9,1-12.14-16; Ps 87; Lc 9,57-62"};
const editorial={"09-30":{ref:"Lc 9,57-62",saint:"Sfântul Ieronim (cca 347–420), preot și învățător al Bisericii, și-a dedicat viața studiului Sfintei Scripturi. A trăit ultimii ani la Betleem și este cunoscut mai ales pentru munca sa de traducere și comentare a Bibliei.",med:"Cuvântul lui Dumnezeu nu este doar un text de cunoscut, ci o chemare de urmat. Exemplul Sfântului Ieronim ne invită să facem loc Scripturii în fiecare zi și să lăsăm ceea ce citim să ne schimbe alegerile.",prayer:"Doamne, dă-ne iubire pentru Cuvântul tău și înțelepciunea de a-l trăi. Prin mijlocirea Sfântului Ieronim, ajută-ne să te căutăm cu inimă sinceră. Amin."}};
function easter(y){let a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),day=(h+l-7*m+114)%31+1;return new Date(y,mo-1,day)}
function add(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x} function iso(d){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")}
function movable(y){let e=easter(y),m={};[[ -46,"Miercurea Cenușii","Zi de post și abstinență"],[-7,"Duminica Floriilor și a Pătimirii Domnului","Duminică"],[-3,"Joia Sfântă","Triduum Pascal"],[-2,"Vinerea Sfântă a Pătimirii Domnului","Triduum Pascal"],[-1,"Sâmbăta Sfântă","Triduum Pascal"],[0,"Învierea Domnului","Solemnitate"],[39,"Înălțarea Domnului","Solemnitate"],[49,"Rusaliile","Solemnitate"],[56,"Preasfânta Treime","Solemnitate"],[60,"Preasfântul Trup și Sânge al lui Cristos","Solemnitate"],[68,"Preasfânta Inimă a lui Isus","Solemnitate"]].forEach(x=>m[iso(add(e,x[0]))]=[x[1],x[2]]);return m}
let selected=new Date(),shown=new Date(selected.getFullYear(),selected.getMonth(),1);
function key(d){return String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")} function celebration(d){return movable(d.getFullYear())[iso(d)]||fixed[key(d)]||null}
function renderDay(d){selected=new Date(d);document.querySelector("#weekday").textContent=roDays[d.getDay()]+",";document.querySelector("#day").textContent=d.getDate();document.querySelector("#month").textContent=roMonths[d.getMonth()]+" "+d.getFullYear();let c=celebration(d),ed=editorial[key(d)]||{};document.querySelector("#feast").textContent=c?c[0]:"Ferie liturgică";document.querySelector("#rank").textContent=c?c[1]:"Timpul liturgic";const rd=d.getFullYear()===2026?readings2026[key(d)]:null;document.querySelector("#gospelRef").textContent=rd||ed.ref||"Lecturile zilei";const ercis=`https://ercis.ro/liturgie/calendar/${d.getFullYear()}/${d.getMonth()+1}/${d.getDate()}`;document.querySelector("#gospelText").innerHTML=(rd?`Lecturi: <strong>${rd}</strong>. `:ed.ref?`Evanghelia: <strong>${ed.ref}</strong>. `:"")+`<a class="source-link" href="${ercis}" target="_blank" rel="noopener">Deschide lecturile complete ale zilei →</a>`;document.querySelector("#saintLife").textContent=ed.saint||(c?"Prezentarea acestei celebrări este în curs de completare.":"În zilele fără o memorie obligatorie, liturgia urmează timpul liturgic și ciclul lecturilor.");document.querySelector("#meditation").textContent=ed.med||"Doamne, ajută-ne să primim Cuvântul tău cu inimă deschisă și să îl transformăm în fapte de iubire.";document.querySelector("#prayer").textContent=ed.prayer||"Doamne, călăuzește-ne astăzi pașii, întărește-ne credința și ajută-ne să purtăm pacea și binele către cei pe care îi întâlnim. Amin.";shown=new Date(d.getFullYear(),d.getMonth(),1)}
function renderCalendar(){document.querySelector("#calendarTitle").textContent=roMonths[shown.getMonth()]+" "+shown.getFullYear();const grid=document.querySelector("#calendarGrid");grid.innerHTML="";let first=(shown.getDay()+6)%7,start=new Date(shown.getFullYear(),shown.getMonth(),1-first);for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let b=document.createElement("button");b.className="day-cell";b.textContent=d.getDate();if(d.getMonth()!=shown.getMonth())b.classList.add("other");if(celebration(d))b.title=celebration(d)[0];let now=new Date();if(d.toDateString()==now.toDateString())b.classList.add("today");if(d.toDateString()==selected.toDateString())b.classList.add("selected");b.onclick=()=>{renderDay(d);renderCalendar();openView("today")};grid.appendChild(b)}}
function openView(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.view===id));if(id==="calendar")renderCalendar()}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>openView(b.dataset.view));document.querySelector("#prevMonth").onclick=()=>{shown.setMonth(shown.getMonth()-1);renderCalendar()};document.querySelector("#nextMonth").onclick=()=>{shown.setMonth(shown.getMonth()+1);renderCalendar()};document.querySelector("#goToday").onclick=()=>{renderDay(new Date());renderCalendar()};renderDay(new Date());renderCalendar();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");