function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function gospelTextPlain(v){if(Array.isArray(v))return v.map(x=>typeof x==="string"?x:(x.t??x.testo??"")).join(" ");if(v&&typeof v==="object")return String(v.testo??"");return String(v||"")}
const GOSPEL_EDITORIAL={
"Lc 9,46-50":{
live:"I discepoli discutono su chi sia il più grande, ma Gesù mette accanto a sé un bambino e cambia completamente la misura della grandezza. Il valore di una persona non dipende dal posto che occupa o dall'attenzione che riceve. Oggi questo Vangelo ci chiede di accorgerci di chi rischia di rimanere ai margini e di smettere di trasformare le relazioni in una gara. Giovanni vorrebbe anche impedire a un uomo di fare il bene perché non appartiene al gruppo dei discepoli; Gesù gli insegna invece a riconoscere il bene anche quando nasce fuori dai nostri confini. <div class=\"gospel-action\"><strong>Un passo concreto per oggi</strong><p>Lascia spazio a una persona che normalmente viene ascoltata poco e riconosci un gesto buono compiuto da qualcuno che non fa parte della tua cerchia.</p></div><p class=\"gospel-question\"><strong>Questa sera chiediti:</strong> «Ho cercato di essere il più importante, oppure ho aiutato qualcuno a sentirsi importante?»</p>",
med:"Gesù conosce il desiderio dei discepoli di essere grandi, ma non li umilia: insegna loro una grandezza nuova. Mette un bambino vicino a sé, quasi a dire che Dio si lascia incontrare dove il mondo vede poca importanza. Poi allarga ancora lo sguardo: anche chi non appartiene al gruppo può essere strumento di bene. Il cuore del discepolo non deve diventare geloso della grazia. Seguire Cristo significa imparare a gioire quando il bene cresce, anche se non porta il nostro nome.",
prayer:"Signore Gesù, liberami dal bisogno di confrontarmi continuamente con gli altri. Quando desidero essere il primo, insegnami la gioia di servire. Apri i miei occhi verso chi è piccolo, dimenticato o poco ascoltato. Liberami anche dalla gelosia spirituale: fa' che sappia riconoscere e ringraziare per il bene ovunque esso nasca. Rendimi semplice, accogliente e capace di costruire comunione. Amen."
},
"Gv 1,47-51":{
live:"Natanaele si sorprende perché Gesù lo conosce prima ancora che lui abbia imparato a conoscere Gesù. Il Vangelo di oggi ci ricorda che la nostra vita non è anonima davanti a Dio: egli vede anche ciò che gli altri non vedono, le domande che custodiamo e il bene nascosto. Ma Gesù non si ferma a ciò che Natanaele ha già sperimentato: gli promette che vedrà cose più grandi. La fede non consiste nel vivere di una sola esperienza passata, ma nel restare disponibili a ciò che Dio può ancora aprire davanti a noi. <div class=\"gospel-action\"><strong>Un passo concreto per oggi</strong><p>Porta davanti a Dio una parte di te che normalmente tieni nascosta e prova ad affrontare la giornata con la disponibilità a lasciarti sorprendere.</p></div><p class=\"gospel-question\"><strong>Questa sera chiediti:</strong> «Credo davvero che Dio mi conosca e possa ancora mostrarmi qualcosa di nuovo?»</p>",
med:"Prima che Natanaele pronunci la sua professione di fede, Gesù gli fa capire di averlo già visto. C'è qualcosa di profondamente consolante in questo incontro: la relazione con Dio non comincia dalla nostra capacità di cercarlo, ma dal suo sguardo che ci precede. Sotto il fico, nel luogo segreto della sua vita, Natanaele era già conosciuto. Anche noi possiamo presentarci a Cristo senza costruire un personaggio. Egli conosce la parte luminosa e quella fragile, e proprio a noi promette un cielo aperto.",
prayer:"Signore Gesù, tu mi conosci prima ancora che io riesca a spiegarti ciò che porto dentro. Tu vedi le mie domande, le speranze, le fragilità e ciò che nessun altro conosce. Donami un cuore sincero come quello di Natanaele e occhi capaci di riconoscere la tua presenza. Quando penso di avere già visto tutto, riapri in me lo stupore e la speranza. Fa' che oggi viva sotto il tuo sguardo senza paura. Amen."
},
"Mt 13,16-17":{
live:"Gesù chiama beati gli occhi che vedono e gli orecchi che ascoltano. Non parla soltanto della capacità fisica di vedere e sentire: invita a riconoscere il dono che abbiamo davanti. Possiamo attraversare giornate piene di cose preziose e accorgercene soltanto quando non ci sono più. Questo Vangelo educa alla gratitudine e all'attenzione. <div class=\"gospel-action\"><strong>Un passo concreto per oggi</strong><p>Fermati davanti a una persona, un incontro o una cosa semplice che normalmente dai per scontata e ringrazia consapevolmente per quel dono.</p></div><p class=\"gospel-question\"><strong>Questa sera chiediti:</strong> «Che cosa di prezioso era davanti ai miei occhi oggi e sono riuscito davvero a vedere?»</p>",
med:"I profeti hanno desiderato vedere ciò che i discepoli hanno davanti agli occhi. Gesù trasforma così il presente in un dono. Anche la nostra fede può diventare abitudine, e ciò che un tempo ci meravigliava rischia di apparirci normale. La beatitudine annunciata da Cristo nasce da uno sguardo risvegliato: vedere la grazia che è già presente e ascoltare una Parola che continua a rivolgersi a noi.",
prayer:"Signore Gesù, apri i miei occhi perché sappia riconoscere i doni che ogni giorno ricevo e troppo facilmente considero scontati. Apri le mie orecchie perché la tua Parola non diventi rumore abituale. Donami gratitudine per le persone, per il tempo e per le possibilità che oggi metti sul mio cammino. Amen."
},
"Gv 12,24-26":{
live:"Gesù usa l'immagine del chicco di grano: per portare frutto deve accettare di essere affidato alla terra. È una parola esigente, perché ci ricorda che molte cose veramente feconde richiedono di lasciare qualcosa di noi: tempo, comodità, orgoglio, controllo. Non ogni perdita è sterile; alcune rinunce, quando nascono dall'amore, diventano vita per altri. <div class=\"gospel-action\"><strong>Un passo concreto per oggi</strong><p>Offri consapevolmente un po' del tuo tempo o della tua comodità per una persona che ne ha bisogno, senza aspettare un vantaggio personale.</p></div><p class=\"gospel-question\"><strong>Questa sera chiediti:</strong> «Che cosa sono disposto a donare perché nella vita di qualcuno possa nascere un frutto buono?»</p>",
med:"Il chicco non produce vita conservandosi intatto, ma consegnandosi. Gesù parla anzitutto di sé e della sua Pasqua, ma rivela anche la forma profonda dell'amore cristiano. La vita custodita soltanto per se stessa si restringe; la vita donata si moltiplica. Questo non significa cercare la sofferenza, ma imparare che amare comporta sempre una parte di dono e di uscita da sé.",
prayer:"Signore Gesù, chicco donato per la vita del mondo, insegnami a non trattenere tutto per me. Liberami dalla paura di perdere quando amare mi chiede tempo, pazienza e sacrificio. Fa' che le mie rinunce non nascano dalla tristezza, ma dalla libertà di chi desidera portare frutto. Rendimi disponibile a seguirti anche quando la via dell'amore costa. Amen."
}
};
function normalizeGospelRef(r){return String(r||"").replace(/^(?:dal\s+)?vangelo\s+secondo\s+\w+\s*/i,"").replace(/[–—]/g,"-").replace(/\s+/g," ").replace(/\s*,\s*/g,",").trim()}
function editorialFor(x){const raw=normalizeGospelRef(x.letture?.vangelo?.riferimento);if(GOSPEL_EDITORIAL[raw])return GOSPEL_EDITORIAL[raw];const key=Object.keys(GOSPEL_EDITORIAL).find(k=>raw.includes(k)||k.includes(raw));return key?GOSPEL_EDITORIAL[key]:null}
function passageSeed(x){const r=normalizeGospelRef(x.letture?.vangelo?.riferimento),d=String(x.data||"");let n=0;for(const c of r+d)n=(n*31+c.charCodeAt(0))>>>0;return n}
function passageFallback(x){
 const r=normalizeGospelRef(x.letture?.vangelo?.riferimento)||"il Vangelo di oggi", t=gospelTextPlain(x.letture?.vangelo?.testo).toLowerCase(), n=passageSeed(x);
 const sets=[
 {re:/guar|ciec|lebb|paralit|malat|sordo|muto/,live:["Gesù non guarda la fragilità come un'etichetta: incontra una persona. Questo passo ci chiede di non ridurre nessuno al suo problema e di diventare presenza che rialza.","La guarigione evangelica comincia spesso da uno sguardo che restituisce dignità. Anche quando non possiamo risolvere tutto, possiamo evitare indifferenza e distanza."],med:["Cristo entra proprio nei luoghi che vorremmo nascondere. La fragilità, consegnata a lui, non è più soltanto una mancanza: può diventare luogo d'incontro, fiducia e rinascita.","Nel Vangelo la sofferenza non rende una persona meno degna di essere vista. Gesù si ferma, ascolta e restituisce relazione prima ancora di ogni altra cosa."],pr:["Signore Gesù, raggiungi ciò che in me ha bisogno di essere guarito. Donami anche occhi capaci di vedere la sofferenza degli altri senza giudicarla. Rendimi presenza che consola e rialza. Amen.","Gesù, medico dell'anima e del corpo, entra nelle mie ferite e insegnami a stare accanto a chi soffre con rispetto, pazienza e speranza. Amen."]},
 {re:/chiam|seguimi|discepol|apostol/,live:["Gesù chiama persone reali, non persone già perfette. Il passo di oggi domanda quale risposta concreta possiamo dare alla sua chiamata dentro la vita che stiamo vivendo.","Seguire Cristo non è soltanto ammirarlo. È permettere alla sua parola di modificare una scelta, una priorità, il modo in cui trattiamo qualcuno."],med:["Ogni vocazione comincia da uno sguardo che precede i nostri meriti. Cristo vede possibilità dove noi vediamo limiti e invita a camminare con lui.","La chiamata di Gesù non toglie la nostra libertà: la risveglia. Ci domanda di lasciare ciò che impedisce al cuore di muoversi verso una vita più vera."],pr:["Signore Gesù, fammi riconoscere la tua chiamata nelle cose concrete di oggi. Dammi libertà per lasciare ciò che mi trattiene e coraggio per seguirti con fedeltà. Amen.","Gesù, quando mi chiami non permettere che paura e abitudine parlino più forte di te. Rendimi disponibile, fedele e generoso nel passo che oggi mi chiedi. Amen."]},
 {re:/risort|vita eterna|morte|sepolcr/,live:["Il Vangelo apre una breccia nella paura più profonda: la morte non possiede l'ultima parola. Questa speranza cambia anche il presente e ci invita a vivere ciò che conta davvero.","Davanti al limite umano Gesù non offre una frase facile, ma la sua presenza. La speranza cristiana ci permette di attraversare il dolore senza chiamarlo bene e senza considerarlo definitivo."],med:["La risurrezione non è un'idea consolatoria aggiunta alla vita: è la promessa che l'amore di Dio non abbandona ciò che ha creato. Anche le nostre notti possono essere attraversate dalla speranza.","Cristo entra nel luogo in cui ogni sicurezza umana finisce e annuncia vita. Meditare questo mistero significa affidargli anche ciò che non possiamo trattenere o comprendere."],pr:["Signore della vita, sostienimi quando incontro il limite, la perdita e la paura. Custodisci chi amo e rendi viva in me la speranza della risurrezione. Amen.","Gesù risorto, entra nelle mie notti e ricordami che nessuna oscurità è più grande della tua vita. Donami speranza e rendimi capace di portarla agli altri. Amen."]},
 {re:/amore|amate|comandamento|prossimo/,live:["Gesù porta la fede nel punto più concreto: il modo in cui amiamo. L'amore evangelico non resta sentimento; diventa tempo donato, verità detta con carità, pazienza e responsabilità.","Il comandamento dell'amore ci impedisce di separare la preghiera dalle relazioni. La verifica della fede passa anche dal modo in cui trattiamo la persona difficile che abbiamo davanti."],med:["L'amore di Cristo non nasce dalla convenienza. È un amore che vede, rimane e si dona. Lasciarci amare da lui è il principio per smettere di usare gli altri come misura del nostro valore.","Dio non ci domanda un amore astratto. Ci consegna persone concrete, con limiti e ferite, attraverso le quali impariamo la pazienza, il perdono e il dono."],pr:["Signore Gesù, insegnami ad amare con gesti veri e non soltanto con intenzioni. Rendimi paziente, sincero e generoso soprattutto dove amare mi costa. Amen.","Gesù, riempi il mio cuore del tuo amore perché non cerchi soltanto chi mi è facile amare. Fammi diventare oggi un segno concreto della tua carità. Amen."]}
 ];
 const z=sets.find(a=>a.re.test(t));if(z){const i=n%z.live.length;return{live:'<h4>'+esc(r)+'</h4><p>'+esc(z.live[i])+'</p><div class="gospel-action"><strong>Un passo concreto per oggi</strong><p>Scegli una persona che oggi rischia di essere ignorata: fermati, ascoltala davvero e falle sentire con un gesto concreto che la sua presenza conta.</p></div><p class="gospel-question"><strong>Questa sera chiediti:</strong> «Dove questo Vangelo ha toccato davvero la mia giornata?»</p>',med:z.med[i],prayer:z.pr[i]}}
 const variants=[
 ["Una Parola da portare nella giornata","Questo brano non chiede di essere soltanto capito. Chiede di essere custodito abbastanza a lungo da raggiungere una decisione, una relazione o una preoccupazione concreta.","Signore Gesù, non lasciare che ascolti la tua Parola distrattamente. Mostrami dove oggi mi chiami a cambiare e dammi la libertà di risponderti. Amen."],
 ["Fermarsi davanti alla Parola","Ogni pagina del Vangelo contiene uno sguardo di Cristo sull'uomo. Rimanere qualche minuto con questo passo significa lasciare che quello sguardo raggiunga anche ciò che oggi viviamo.","Gesù, apri il mio cuore alla tua Parola. Fa' che ciò che leggo diventi luce nelle mie scelte e carità nel modo in cui incontro gli altri. Amen."],
 ["Dal Vangelo alla vita","La Parola diventa feconda quando attraversa la distanza tra ciò che ascoltiamo e ciò che facciamo. Oggi possiamo permettere a questo brano di cambiare almeno una piccola cosa.","Signore, dammi un ascolto vero e un cuore disponibile. Aiutami a trasformare il Vangelo di oggi in un gesto, una parola o una scelta che porti il tuo bene. Amen."]
 ],v=variants[n%variants.length];
 return{live:'<h4>'+esc(v[0])+'</h4><p>Nel passo <strong>'+esc(r)+'</strong> prova a notare quale parola, gesto o incontro di Gesù ti trattiene più a lungo.</p><div class="gospel-action"><strong>Un passo concreto per oggi</strong><p>Rileggi il brano una seconda volta e scegli una sola frase da ricordare durante la giornata.</p></div><p class="gospel-question"><strong>Questa sera chiediti:</strong> «Che cosa ha cambiato in me questa Parola?»</p>',med:v[1],prayer:v[2]}
}
function reflectionFor(x){return editorialFor(x)||passageFallback(x)}
function liveGospelToday(x){
const editorial=reflectionFor(x);if(editorial)return editorial.live;
const ref=x.letture?.vangelo?.riferimento||"";
const t=gospelTextPlain(x.letture?.vangelo?.testo).toLowerCase();
const themes=[
{re:/bambin|fanciull|piccol|maggiore|grande/,title:"La grandezza che non ha bisogno di imporsi",insight:"Gesù rovescia il nostro modo abituale di misurare le persone. Nel Vangelo il più grande non è chi occupa più spazio, riceve più riconoscimenti o riesce a imporsi sugli altri. Gesù mette al centro chi è piccolo e ci chiede di riconoscere proprio lì una presenza preziosa.",life:"Anche nelle nostre giornate nasce facilmente il desiderio di essere considerati, ascoltati o riconosciuti. Quando questo desiderio diventa una gara, però, rischiamo di non vedere più chi abbiamo davanti. Accogliere il piccolo significa lasciare spazio, ascoltare, servire e fare del bene anche quando nessuno se ne accorgerà.",act:"Oggi prova a fare qualcosa di buono senza raccontarlo a nessuno. Può essere aiutare un collega, ascoltare con pazienza una persona, lasciare spazio a chi parla meno o rinunciare ad avere l'ultima parola.",q:"Sto cercando di essere più importante degli altri, oppure sto imparando a farmi vicino agli altri?"},
{re:/perdon|misericord|debito/,title:"Lasciare che la misericordia abbia l'ultima parola",insight:"Il perdono evangelico non dice che il male ricevuto sia irrilevante. Gesù ci mostra piuttosto che una ferita non deve diventare la prigione nella quale continuiamo a vivere. La misericordia interrompe la catena per cui un'offesa genera un'altra offesa.",life:"Ci sono parole che continuiamo a ripetere nella mente e persone alle quali abbiamo già risposto cento volte dentro di noi. Perdonare può richiedere tempo, ma il primo passo è decidere che il rancore non guiderà ogni nostra scelta.",act:"Oggi evita di alimentare una vecchia ferita. Se è possibile, compi un piccolo gesto di pace; se non lo è ancora, prova almeno a pregare senza augurare il male alla persona che ti ha ferito.",q:"Quale ferita sto permettendo di decidere troppo della mia vita?"},
{re:/paura|temet|fede|cred|fiducia/,title:"Fare un passo anche quando non vediamo tutto",insight:"La fede del Vangelo non è la certezza che ogni problema sparirà. È la decisione di non consegnare alla paura l'ultima parola. Gesù invita a fidarsi mentre la strada è ancora davanti a noi, non soltanto quando conosciamo già il risultato.",life:"Anche oggi possiamo portare una preoccupazione che nessuno vede: il lavoro, la famiglia, una decisione, una persona amata o qualcosa che non possiamo controllare. La fede non ci chiede di fingere che questa inquietudine non esista; ci invita a consegnarla a Dio e a fare con responsabilità ciò che dipende da noi.",act:"Scegli una preoccupazione concreta. Domandati quale piccolo passo puoi compiere oggi e fallo senza aspettare di sentirti completamente sicuro.",q:"Oggi ho lasciato che fosse la paura a guidarmi, oppure ho fatto almeno un passo nella fiducia?"},
{re:/povero|affam|assetat|nudo|forestier|malat/,title:"Accorgerci di chi rischia di diventare invisibile",insight:"Gesù porta lo sguardo verso chi normalmente rimane ai margini. Il Vangelo non permette una fede fatta soltanto di parole: l'incontro con Dio passa anche attraverso la fame, la solitudine, la fragilità e il bisogno concreto dell'altro.",life:"È possibile attraversare un'intera giornata senza vedere davvero le persone. Possiamo essere occupati, stanchi o presi dai nostri problemi e non accorgerci che qualcuno vicino a noi sta chiedendo attenzione senza pronunciare una parola.",act:"Guarda con più attenzione le persone che incontrerai oggi. Scegline una alla quale offrire tempo, ascolto o un aiuto concreto senza aspettare qualcosa in cambio.",q:"Chi ho davanti ogni giorno ma rischio di non vedere più davvero?"},
{re:/serv|servo|piedi/,title:"La forza nascosta del servizio",insight:"Gesù lega la vera grandezza alla capacità di servire. Non è debolezza: significa essere abbastanza liberi da non aver bisogno che tutto ruoti intorno a noi.",life:"Molte delle cose che tengono insieme una famiglia, un luogo di lavoro o un'amicizia sono gesti che quasi nessuno applaude. Preparare, aiutare, aspettare, ascoltare, sistemare ciò che altri hanno lasciato: il Vangelo dà valore proprio a questa fedeltà nascosta.",act:"Fai oggi un servizio che normalmente aspetteresti da qualcun altro, senza lamentarti e senza cercare riconoscimento.",q:"Quando aiuto qualcuno, lo faccio per amore o perché desidero essere riconosciuto?"},
{re:/preg|padre nostro|chiedete|bussate/,title:"Restare davanti a Dio senza maschere",insight:"Gesù presenta la preghiera come una relazione, non come una formula magica. Pregare significa portare davanti a Dio ciò che siamo davvero: gratitudine, paura, desideri, stanchezza e perfino le domande alle quali non sappiamo dare risposta.",life:"Spesso diciamo di non avere tempo per pregare, mentre la nostra mente trova tempo per ripetere continuamente le stesse preoccupazioni. La preghiera può cominciare proprio lì, trasformando quel pensiero insistente in una parola affidata a Dio.",act:"Prenditi cinque minuti senza telefono e senza altre distrazioni. Non cercare parole perfette: racconta a Dio con semplicità ciò che oggi pesa di più nel tuo cuore.",q:"Quando prego, sto davvero parlando con Dio oppure sto soltanto pronunciando parole?"},
{re:/seme|semin|vigna|frutto|albero/,title:"Il bene cresce anche quando non lo vediamo",insight:"Le immagini del seme e del frutto ci ricordano che Dio lavora spesso attraverso processi lenti. Non tutto ciò che è importante produce risultati immediati.",life:"Viviamo in un tempo che ci abitua a misurare subito i risultati. Il Vangelo insegna invece la pazienza di chi semina bene anche quando non può ancora vedere il raccolto.",act:"Riprendi oggi una cosa buona che rischiavi di abbandonare perché i risultati tardano: una relazione, un impegno, una preghiera, un cambiamento personale.",q:"Quale seme buono devo continuare a coltivare senza pretendere risultati immediati?"},
{re:/nemic|perseguit|odia|guancia/,title:"Non diventare simili al male che riceviamo",insight:"Amare il nemico è una delle parole più esigenti di Gesù. Non significa approvare l'ingiustizia né rinunciare a proteggersi. Significa rifiutare che il male ricevuto trasformi anche noi in persone dominate dall'odio.",life:"Quando qualcuno ci ferisce, la reazione immediata è restituire la stessa durezza. Il Vangelo apre una possibilità diversa: difendere ciò che è giusto senza perdere la nostra umanità.",act:"Se oggi nasce un conflitto, prova a interrompere l'automatismo della risposta aggressiva. Prenditi qualche secondo e scegli parole ferme, ma non umilianti.",q:"Il modo in cui reagisco al male mi rende più libero oppure mi rende simile a ciò che condanno?"}
];
const found=themes.find(z=>z.re.test(t))||{title:"Lasciare che la Parola entri nella vita",insight:"Il Vangelo di oggi non è soltanto il racconto di qualcosa accaduto lontano nel tempo. Attraverso le parole e i gesti di Gesù ci viene chiesto di guardare la nostra vita con maggiore verità e di riconoscere dove abbiamo bisogno di cambiare.",life:"La Parola diventa viva quando smette di essere soltanto una lettura e raggiunge le nostre relazioni, le decisioni, il lavoro, la famiglia e il modo in cui trattiamo le persone.",act:"Rileggi lentamente una frase del Vangelo che ti ha colpito. Portala con te durante la giornata e, prima di una decisione o di una risposta importante, chiediti che cosa cambierebbe se la prendessi sul serio.",q:"Quale parola del Vangelo di oggi sento rivolta personalmente a me?"};
return '<h4>'+esc(found.title)+'</h4><p>'+esc(found.insight)+'</p><p>'+esc(found.life)+'</p><div class="gospel-action"><strong>Un passo concreto per oggi</strong><p>'+esc(found.act)+'</p></div><p class="gospel-question"><strong>Questa sera chiediti:</strong> «'+esc(found.q)+'»</p>'
}
function spiritualTheme(x){
const t=gospelTextPlain(x.letture?.vangelo?.testo).toLowerCase();
const themes=[
{re:/bambin|fanciull|piccol|maggiore|grande/,m:"Gesù, mettendo al centro i piccoli, ci libera dalla necessità di essere sempre i primi. Davanti a Dio non conta l'immagine che riusciamo a costruire di noi stessi, ma la disponibilità del cuore. La vera grandezza può nascondersi in un gesto che nessuno vede, nella pazienza con chi è fragile, nella capacità di fare spazio invece di occuparlo. Restare piccoli davanti a Dio non significa svalutarsi: significa riconoscere che tutto è dono e che anche l'altra persona è preziosa ai suoi occhi.",p:"Signore Gesù, liberami dal bisogno di essere sempre riconosciuto e apprezzato. Donami un cuore semplice, capace di vedere chi rimane ai margini e di servire senza cercare ricompensa. Quando nasce in me il desiderio di essere superiore agli altri, ricordami che davanti a te la vera grandezza è amare. Fa' che oggi sappia accogliere, ascoltare e fare spazio. Amen."},
{re:/perdon|misericord|debito/,m:"La misericordia di Dio raggiunge proprio i luoghi interiori che facciamo più fatica a consegnargli. Perdonare non cancella ciò che è accaduto e non rende giusto ciò che ci ha ferito; impedisce però alla ferita di diventare il centro della nostra vita. Gesù ci invita a ricevere il perdono e, lentamente, a lasciarlo passare attraverso di noi. Talvolta il primo miracolo del perdono è semplicemente smettere di desiderare che l'altro soffra quanto abbiamo sofferto noi.",p:"Signore misericordioso, tu conosci le ferite che porto nel cuore e sai quanto alcune siano difficili da lasciare andare. Non permettere che il rancore diventi più forte dell'amore. Insegnami a perdonare senza negare la verità e a chiedere perdono quando sono io ad aver ferito. Metti pace dove da solo non riesco ad arrivare. Amen."},
{re:/paura|temet|fede|cred|fiducia/,m:"La fede non nasce quando tutte le domande hanno trovato risposta. Spesso comincia proprio quando, pur non vedendo tutta la strada, scegliamo di affidarci. Gesù non ci chiede di essere persone senza paura, ma di non permettere alla paura di diventare il nostro padrone. Possiamo portare a Dio anche l'incertezza, perché credere significa camminare con lui dentro la realtà, non fuggire dalla realtà.",p:"Signore Gesù, tu conosci ciò che oggi mi preoccupa e ciò che non riesco a controllare. Quando la paura restringe il mio sguardo, aiutami a ricordare che non cammino da solo. Dammi la serenità per accettare ciò che non dipende da me, il coraggio per affrontare ciò che posso cambiare e la fede per affidarti ciò che ancora non comprendo. Amen."},
{re:/povero|affam|assetat|nudo|forestier|malat/,m:"Nel Vangelo Dio non rimane lontano dalla fragilità umana. Gesù ci insegna a riconoscerlo proprio là dove una persona ha fame, è sola, malata, dimenticata o bisognosa di dignità. La vita spirituale diventa allora uno sguardo nuovo: non attraversare il mondo chiedendoci soltanto che cosa possiamo ricevere, ma imparare a domandarci chi, accanto a noi, ha bisogno che ci fermiamo.",p:"Signore Gesù, apri i miei occhi perché non passi accanto al dolore senza accorgermene. Rendimi attento a chi è solo, fragile o dimenticato. Dammi mani disponibili ad aiutare, parole capaci di consolare e un cuore che non giudichi la povertà degli altri. Fa' che sappia riconoscere il tuo volto nelle persone che incontrerò oggi. Amen."},
{re:/serv|servo|piedi/,m:"Gesù rivela una forma di potere completamente diversa: chinarsi per servire. Il servizio evangelico non umilia chi lo compie; lo rende libero dalla necessità di stare sempre al centro. Molto del bene che sostiene il mondo nasce così, in silenzio: qualcuno prepara, ascolta, accompagna, pulisce, aspetta, cura. Sono gesti ordinari che, vissuti nell'amore, diventano straordinari agli occhi di Dio.",p:"Signore Gesù, tu hai scelto la via del servizio. Toglimi dal cuore l'orgoglio che misura ciò che faccio in base agli applausi ricevuti. Rendimi disponibile nelle piccole cose, paziente quando servire costa e generoso quando nessuno se ne accorge. Fa' che le mie mani possano diventare oggi strumenti del tuo amore. Amen."},
{re:/preg|padre nostro|chiedete|bussate/,m:"Pregare significa permettere a Dio di entrare nella verità della nostra giornata. Non occorrono sempre molte parole. A volte la preghiera più sincera è un nome pronunciato davanti a Dio, una paura affidata, un grazie detto lentamente o perfino un silenzio nel quale smettiamo finalmente di fuggire da noi stessi. Gesù ci invita a pregare con la fiducia di chi sa di essere ascoltato.",p:"Padre buono, eccomi davanti a te così come sono. Conosci ciò che riesco a dire e anche ciò per cui non trovo parole. Accogli le persone che porto nel cuore, le mie preoccupazioni e la mia gratitudine. Insegnami a cercarti non soltanto quando ho bisogno di qualcosa, ma perché desidero vivere alla tua presenza. Amen."},
{re:/seme|semin|vigna|frutto|albero/,m:"Dio ama iniziare dalle cose piccole. Un seme sembra insignificante, eppure porta dentro di sé una vita che ha bisogno di tempo. Anche noi vorremmo vedere subito i risultati delle nostre scelte, della preghiera e del bene che facciamo. Il Vangelo ci educa invece alla fedeltà: seminare ciò che è buono, custodirlo e lasciare a Dio anche il tempo della crescita.",p:"Signore, insegnami la pazienza del seminatore. Quando non vedo risultati, proteggimi dallo scoraggiamento. Aiutami a continuare a seminare bene nelle parole, nel lavoro, nelle relazioni e nelle scelte quotidiane. Donami fiducia nei piccoli inizi e rendimi fedele anche quando il frutto tarda ad arrivare. Amen."},
{re:/nemic|perseguit|odia|guancia/,m:"Gesù non banalizza il male, ma ci impedisce di consegnargli il nostro cuore. Amare chi ci è ostile non significa accettare abusi o rinunciare alla giustizia. Significa custodire dentro di noi uno spazio nel quale l'odio non riesca a diventare padrone. È una libertà difficile, che spesso dobbiamo chiedere a Dio prima ancora di riuscire a viverla.",p:"Signore Gesù, quando sono ferito aiutami a non diventare prigioniero dell'odio. Dammi forza per difendere ciò che è giusto senza perdere la misericordia. Custodisci le mie parole dalla vendetta e guarisci lentamente ciò che dentro di me fa ancora male. Dove oggi c'è conflitto, rendimi capace di non aggiungere altro male. Amen."}
];
return themes.find(z=>z.re.test(t))||{m:"La Parola di oggi ci invita a fermarci abbastanza a lungo da permetterle di raggiungere la nostra vita reale. Il Vangelo non è soltanto qualcosa da comprendere con la mente: domanda uno spazio nel cuore, nelle relazioni e nelle decisioni. Una frase ascoltata con attenzione può diventare luce proprio nel punto in cui siamo più confusi. Restiamo qualche momento davanti a questa Parola senza fretta, chiedendo a Dio di mostrarci ciò che oggi abbiamo bisogno di vedere.",p:"Signore Gesù, fa' che la tua Parola non scivoli via dalla mia giornata. Donami un cuore capace di ascoltare e il coraggio di cambiare ciò che deve essere cambiato. Guidami nelle decisioni, custodisci le persone che amo e rendimi capace di portare nel mondo un poco della luce che oggi ricevo da te. Amen."}
}
function meditation(x){return reflectionFor(x).med}
function prayer(x){return reflectionFor(x).prayer}

export function dailyReflection(x){return reflectionFor(x)}
